name: Playwright Python Test

on:
  workflow_dispatch:

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          pip install -r requirements.txt || true  # if you have a requirements.txt
          playwright install

      - name: Run Playwright script
        run: python hello.py "${{ github.event.inputs.message }}"

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshot
          path: screenshot_*.png
